### ISSUE TITLE
需要输入两次参与抽奖才能正确进入抽奖队列

### ISSUE THREAD

**Issue by Aegiszhy** [Roll-Bot-Project/roll-bot#2]
# 问题描述
&emsp;&emsp;在通过`roll add`设置一个抽奖任务（自定义参与抽奖口令）后，别人参与抽奖时需要输入两次参与抽奖的口令才能进入抽奖队列，仅输入一次抽奖会于控制台报一个错。

# 设备环境
| 系统 | koishi版本 | node版本 | npm版本 | yarn版本 | 类型 |
| -- | -- | -- | -- | -- | -- |
| windows 11 | 4.18.0 | v20.14.0 | 10.8.1 | 1.22.22 | Koishi Desktop |
| centos 7 | 4.18.0 | v20.17.0 | 10.8.2 | 无 | 模板项目 |
# 触发流程
* 先使用`roll add`指令创建一个抽奖。
* 让群友输入一次`roll join ****` 参与抽奖，<mark>此时控制台会输出错误 `Cannot read properties of undefined (reading 'aid')`</mark>，并且Bot也没提示 `成功加入编号为 **** 的抽奖` ，通过 `roll member ****` 来查看参与人员，并没有发现当事人加入了抽奖队列。
* 再让群友输入一次`roll join ****` 参与抽奖，此时Bot会提示 `成功加入编号为 **** 的抽奖` ，并且通过 `roll member ****` 来查看当时人已经加入了抽奖队列。

# 相关日志
```
...
2024-10-03 13:20:28 [W] app TypeError: Cannot read properties of undefined (reading 'aid')
                            at Proxy.<anonymous> (/home/Aegiszhy/koishi-app-2/node_modules/koishi-plugin-roll-bot/lib/index.js:1746:61)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
...
```
# 代码定位
![image](https://github.com/user-attachments/assets/1fd5a260-de48-4387-bc99-5bbb98986a19)

# BUG示例
![image](https://github.com/user-attachments/assets/d93719bf-6f24-47e6-9320-d1647654962c)
![image](https://github.com/user-attachments/assets/549d0965-6488-4122-9aa6-0d09f2c2d646)
![image](https://github.com/user-attachments/assets/a8d6e1c7-406d-4799-85ac-e43552920d66)
![image](https://github.com/user-attachments/assets/5e4bf93b-40f4-4b6e-a5eb-8c36ee436797)

**Comment by Logthm** [comment]
有可能是新账号第一次没法拿到aid导致的？我这边用旧账号测试没法复现，但是没测新账号。

**Comment by Aegiszhy** [comment]
&emsp;&emsp;应该是新账号导致的aid的错误，因为是部署了bot到一个新群聊里去了，并开启了该插件，所以还真应该是新用户未被记录。这个问题似乎不痛不痒，但是要不要未来考虑加个提示信息呢？

**Comment by Logthm** [comment]
> 应该是新账号导致的aid的错误，因为是部署了bot到一个新群聊里去了，并开启了该插件，所以还真应该是新用户未被记录。这个问题似乎不痛不痒，但是要不要未来考虑加个提示信息呢？

发 1.2.5 了，你可以更新试试。现在遇到没有 aid 的情况会重试 3 次，仍然找不到也会有提示信息了。
