### ISSUE TITLE
在使用 qq 官方机器人时查询开奖结果 出现未知错误

### ISSUE THREAD

**Issue by IsHPDuwu** [Roll-Bot-Project/roll-bot#3]
![Screenshot_2024-10-19-06-14-32-476_com tencent mobileqq-edit](https://github.com/user-attachments/assets/ab1193c2-ca3b-4dff-99ee-35fdd3e8d0fb)

日志无相关输出。

已多次尝试，未果。

**Comment by Logthm** [comment]
我没有官方的 qq 机器人，暂时没法测试。可能是官方对于获取 qq 号的限制导致的？你可以创建一个抽奖然后在数据库截图下 roll 和 roll_creator 表吗。

**Comment by IsHPDuwu** [comment]
现在我不太方便拿到数据库


qq 官方 bot 是不允许获取 qq 号码的


可以给 qq 端专门使用 用户ID 吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月19日(周六) 中午12:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Roll-Bot-Project/roll-bot] 在使用 qq 官方机器人时查询开奖结果 出现未知错误 (Issue #3)




 
我没有官方的 qq 机器人，暂时没法测试。可能是官方对于获取 qq 号的限制导致的？你可以创建一个抽奖然后在数据库截图下 roll 和 roll_creator 表吗。

**Comment by Logthm** [comment]
快速看了下官方机器人的限制，似乎连用户 id 都没法获取？那可能没法很好的实现抽奖功能。

**Comment by IsHPDuwu** [comment]
我们可以使用 inspect 指令的用户 id 吗

![Screenshot_2024-10-21-19-16-20-162_com tencent mobileqq-edit](https://github.com/user-attachments/assets/aaca578e-9fc1-46e2-b969-1da106a054cf)

**Comment by IsHPDuwu** [comment]
比如说我们可以暂时使用 session.userId

**Comment by Logthm** [comment]
问题在于抽奖结果怎么办，每个人记自己的 id 不太现实。

**Comment by IsHPDuwu** [comment]
我们可以在 join 的时候给出用户此 id，如果忘了可以再 inspect。


这好像是唯一的方案了，吧？


或者给大家一个 uuid，我们在用这个的项目是用 uuid 作为 token 的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月21日(周一) 晚上10:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Roll-Bot-Project/roll-bot] 在使用 qq 官方机器人时查询开奖结果 出现未知错误 (Issue #3)




 
问题在于抽奖结果怎么办，每个人记自己的 id 不太现实。

**Comment by Logthm** [comment]
我有空注册个 bot 测试下具体情况再想想怎么实现。
如果没有比较方便的办法的话可能不会考虑支持。要用户自己记 uuid 这么麻烦本身就偏离用 bot 的原意了。

**Comment by IsHPDuwu** [comment]
我的建议是使用 用户 id&nbsp;


这（应该）是在 qq 平台下唯一可使用的 用户唯一标识符





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月22日(周二) 晚上8:15
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Roll-Bot-Project/roll-bot] 在使用 qq 官方机器人时查询开奖结果 出现未知错误 (Issue #3)




 
我有空注册个 bot 测试下具体情况再想想怎么实现。
 如果没有比较方便的办法的话可能不会考虑支持。要用户自己记 uuid 这么麻烦本身就偏离用 bot 的原意了。

**Comment by Logthm** [comment]
> 我的建议是使用 用户 id&nbsp; 这（应该）是在 qq 平台下唯一可使用的 用户唯一标识符
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年10月22日(周二) 晚上8:15 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [Roll-Bot-Project/roll-bot] 在使用 qq 官方机器人时查询开奖结果 出现未知错误 (Issue #3) 我有空注册个 bot 测试下具体情况再想想怎么实现。 如果没有比较方便的办法的话可能不会考虑支持。要用户自己记 uuid 这么麻烦本身就偏离用 bot 的原意了。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

是的。。。我自己创建了个官方 bot 测试了一下，群聊场景里只能拿到 `用户ID` 和 `头像`，而且据文档的说法，这个 `用户ID` 在不同群还是不统一的。不过理论上可以加个绑定指令来手动建立 `qq号` 和 `用户ID` 的关联。

以及我看到似乎有人的 随机数生成 bot 因为“涉嫌赌博等内容”没有过审核，我感觉抽奖这种功能很可能无法通过官方的上架审核。 所以短期内我应该是不会支持官方 bot 了。
